services:
  - type: web
    name: express-pdf-generator
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /